language: java
services:
- docker
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --region eu-west-1)
- mvn clean
install: mvn test package -P calc,docker,monitoring
after_success:
- docker run -d --name splunk-devops-demo -p 8080:8080 hazgar/splunk-devops-demo
- mvn clean test verify -P extest,local,perftest
- docker tag hazgar/splunk-devops-demo:latest 242698106395.dkr.ecr.eu-west-1.amazonaws.com/s4x/devops-demo:latest
- docker push 242698106395.dkr.ecr.eu-west-1.amazonaws.com/s4x/devops-demo:latest
- docker stop splunk-devops-demo
- docker stop monitoring
- docker rm splunk-devops-demo
- docker rm monitoring
env:
  global:
    AWS_ACCESS_KEY_ID:
      - secure: MGMXHkWXj/qyRU83FpfAnEMWU8lsCfsGVhmMhFkNPZ213mFUwT+yW6q3u/vLrhViXZbjuGQl9nyZO193CEdrnCZWQMJcVZQkmeK+xFd6jv6sUB9be416nzaKC8z06wBkEFUu1qA2z9MY3KEyz1pdda5qIbTQidjhjJe2HSq750c=
    AWS_SECRET_ACCESS_KEY:
      - secure: TQp3zsgqGH9J78dndBODwytg9PMlEKVyL2AuJ4r6+TQaDfNkgIMpDvlL1Y/yVwHOws2DdFE21ddXrODWcHTukwBUn3X4mIR2Gq/ihIJla25ZgelTDeQ4V+bSr37TqEaWiqvhas8J1wmVTTaeRy1F+P71VYw1Uuv3jEN/1DJARng=
