language: java
services:
- docker
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --region eu-west-1)
- mvn clean
install: mvn test package -P calc,docker,front,monitoring
after_success:
- docker run -d --name splunk-devops-demo -p 8080:8080 hazgar/splunk-devops-demo
- mvn clean test verify -P extest,local,perftest
- docker tag hazgar/splunk-devops-demo:latest 242698106395.dkr.ecr.eu-west-1.amazonaws.com/s4x/devops-demo:latest
- docker push 242698106395.dkr.ecr.eu-west-1.amazonaws.com/s4x/devops-demo:latest
- docker tag hazgar/splunk-devops-demo-front:latest 242698106395.dkr.ecr.eu-west-1.amazonaws.com/s4x/devops-demo-front:latest
- docker push 242698106395.dkr.ecr.eu-west-1.amazonaws.com/s4x/devops-demo-front:latest
- docker stop splunk-devops-demo
- docker stop monitoring
- docker rm splunk-devops-demo
- docker rm monitoring
env:
  global:
  - secure: IqgmnKD48arijpA45vfATqMC0gcCUHhJMHWXy7KpvTH9T7pzTQQfYuL1VoAC6E//gEaCki6sMG2OMUgYDYpj1rf9ZwTrL9R640goEmpaQwb87bl2jwZdgSOyuWEpDZUG3TkrLEtuBnJyJ5npHJVmynikNirK6WyzKasW2yuqaV4=
  - secure: Zz0gE3otU/TCVnSlECiTmvJ4GsS0rKKtJWowf7Ss63emQKFxcTf/1OpfNJWMpucK4/Soa077rvh06x4VTPeiyyguKFTdNoyO/n6fxOyhgriS+mrKmKtvnvI1Rxet7vaN0iV2MZMchrSdy5XUz9hyE3QIF7jiYjXzXhHNl6gAIQ8=
