language: java
services:
 - docker
before_install: mvn clean
install: mvn test package -P calc,docker
after_success:
 - docker run -d --name splunk-devops-demo --log-driver=splunk --log-opt splunk-token=601E28D2-2266-4B5D-8002-1D9727CFC69B --log-opt splunk-url=https://54.194.105.157:8088 --log-opt splunk-insecureskipverify=true -p 8080:8080 hazgar/splunk-devops-demo
 - mvn clean test verify -P extest,local,perftest
 - docker stop splunk-devops-demo
 - docker rm splunk-devops-demo

